create table sqlite_master
(
    type     TEXT,
    name     TEXT,
    tbl_name TEXT,
    rootpage INT,
    sql      TEXT
);

INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'django_migrations', 'django_migrations', 2, 'CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'sqlite_sequence', 'sqlite_sequence', 3, 'CREATE TABLE sqlite_sequence(name,seq)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'django_content_type', 'django_content_type', 6, 'CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'django_content_type_app_label_model_76bd3d3b_uniq', 'django_content_type', 4, 'CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'auth_group_permissions', 'auth_group_permissions', 9, 'CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'auth_group_permissions_group_id_permission_id_0cd325b0_uniq', 'auth_group_permissions', 12, 'CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', 13, 'CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', 14, 'CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'auth_permission', 'auth_permission', 15, 'CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'auth_permission_content_type_id_codename_01ab375a_uniq', 'auth_permission', 5, 'CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'auth_permission_content_type_id_2f476e4b', 'auth_permission', 10, 'CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'auth_group', 'auth_group', 11, 'CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_auth_group_1', 'auth_group', 16, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'AuthManager_userprofile', 'AuthManager_userprofile', 7, 'CREATE TABLE "AuthManager_userprofile" ("last_login" datetime NULL, "is_superuser" bool NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "id" char(32) NOT NULL PRIMARY KEY, "username" varchar(255) NOT NULL, "email" varchar(255) NOT NULL UNIQUE, "password" varchar(255) NOT NULL, "first_name" varchar(255) NOT NULL, "last_name" varchar(255) NOT NULL, "country" varchar(100) NULL, "state" varchar(100) NULL, "city" varchar(100) NULL, "date_joined" datetime NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_AuthManager_userprofile_1', 'AuthManager_userprofile', 8, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_AuthManager_userprofile_2', 'AuthManager_userprofile', 17, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'AuthManager_userprofile_groups', 'AuthManager_userprofile_groups', 18, 'CREATE TABLE "AuthManager_userprofile_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userprofile_id" char(32) NOT NULL REFERENCES "AuthManager_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'AuthManager_userprofile_user_permissions', 'AuthManager_userprofile_user_permissions', 19, 'CREATE TABLE "AuthManager_userprofile_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userprofile_id" char(32) NOT NULL REFERENCES "AuthManager_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'AuthManager_userprofile_groups_userprofile_id_group_id_c5d7c14a_uniq', 'AuthManager_userprofile_groups', 21, 'CREATE UNIQUE INDEX "AuthManager_userprofile_groups_userprofile_id_group_id_c5d7c14a_uniq" ON "AuthManager_userprofile_groups" ("userprofile_id", "group_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'AuthManager_userprofile_groups_userprofile_id_81a2e4a5', 'AuthManager_userprofile_groups', 23, 'CREATE INDEX "AuthManager_userprofile_groups_userprofile_id_81a2e4a5" ON "AuthManager_userprofile_groups" ("userprofile_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'AuthManager_userprofile_groups_group_id_b38bd943', 'AuthManager_userprofile_groups', 24, 'CREATE INDEX "AuthManager_userprofile_groups_group_id_b38bd943" ON "AuthManager_userprofile_groups" ("group_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'AuthManager_userprofile_user_permissions_userprofile_id_permission_id_49a225f1_uniq', 'AuthManager_userprofile_user_permissions', 25, 'CREATE UNIQUE INDEX "AuthManager_userprofile_user_permissions_userprofile_id_permission_id_49a225f1_uniq" ON "AuthManager_userprofile_user_permissions" ("userprofile_id", "permission_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'AuthManager_userprofile_user_permissions_userprofile_id_f93d9c7c', 'AuthManager_userprofile_user_permissions', 26, 'CREATE INDEX "AuthManager_userprofile_user_permissions_userprofile_id_f93d9c7c" ON "AuthManager_userprofile_user_permissions" ("userprofile_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'AuthManager_userprofile_user_permissions_permission_id_191b5a48', 'AuthManager_userprofile_user_permissions', 27, 'CREATE INDEX "AuthManager_userprofile_user_permissions_permission_id_191b5a48" ON "AuthManager_userprofile_user_permissions" ("permission_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'django_admin_log', 'django_admin_log', 31, 'CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" char(32) NOT NULL REFERENCES "AuthManager_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', 28, 'CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'django_admin_log_user_id_c564eba6', 'django_admin_log', 29, 'CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'django_session', 'django_session', 30, 'CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_django_session_1', 'django_session', 32, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'django_session_expire_date_a5c62663', 'django_session', 33, 'CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'token_blacklist_blacklistedtoken', 'token_blacklist_blacklistedtoken', 35, 'CREATE TABLE "token_blacklist_blacklistedtoken" ("blacklisted_at" datetime NOT NULL, "token_id" bigint NOT NULL UNIQUE REFERENCES "token_blacklist_outstandingtoken" ("id") DEFERRABLE INITIALLY DEFERRED, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_token_blacklist_blacklistedtoken_1', 'token_blacklist_blacklistedtoken', 36, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'token_blacklist_outstandingtoken', 'token_blacklist_outstandingtoken', 39, 'CREATE TABLE "token_blacklist_outstandingtoken" ("token" text NOT NULL, "created_at" datetime NULL, "expires_at" datetime NOT NULL, "user_id" char(32) NULL REFERENCES "AuthManager_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED, "jti" varchar(255) NOT NULL UNIQUE, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_token_blacklist_outstandingtoken_1', 'token_blacklist_outstandingtoken', 40, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'token_blacklist_outstandingtoken_user_id_83bc629a', 'token_blacklist_outstandingtoken', 34, 'CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" ("user_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'UserManager_userrecommendationhistory', 'UserManager_userrecommendationhistory', 56, 'CREATE TABLE "UserManager_userrecommendationhistory" ("id" char(32) NOT NULL PRIMARY KEY, "recommendation" text NOT NULL CHECK ((JSON_VALID("recommendation") OR "recommendation" IS NULL)), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "user_id" char(32) NOT NULL REFERENCES "AuthManager_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_UserManager_userrecommendationhistory_1', 'UserManager_userrecommendationhistory', 57, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userrecommendationhistory_user_id_aafe3c13', 'UserManager_userrecommendationhistory', 71, 'CREATE INDEX "UserManager_userrecommendationhistory_user_id_aafe3c13" ON "UserManager_userrecommendationhistory" ("user_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'RecommendationManager_cuisine', 'RecommendationManager_cuisine', 72, 'CREATE TABLE "RecommendationManager_cuisine" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "description" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'UserManager_userpreferences_preferred_cuisine', 'UserManager_userpreferences_preferred_cuisine', 37, 'CREATE TABLE "UserManager_userpreferences_preferred_cuisine" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userpreferences_id" char(32) NOT NULL REFERENCES "UserManager_userpreferences" ("id") DEFERRABLE INITIALLY DEFERRED, "cuisine_id" bigint NOT NULL REFERENCES "RecommendationManager_cuisine" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_cuisine_userpreferences_id_cuisine_id_4a0951df_uniq', 'UserManager_userpreferences_preferred_cuisine', 38, 'CREATE UNIQUE INDEX "UserManager_userpreferences_preferred_cuisine_userpreferences_id_cuisine_id_4a0951df_uniq" ON "UserManager_userpreferences_preferred_cuisine" ("userpreferences_id", "cuisine_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_cuisine_userpreferences_id_3075b160', 'UserManager_userpreferences_preferred_cuisine', 51, 'CREATE INDEX "UserManager_userpreferences_preferred_cuisine_userpreferences_id_3075b160" ON "UserManager_userpreferences_preferred_cuisine" ("userpreferences_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_cuisine_cuisine_id_b8a492d0', 'UserManager_userpreferences_preferred_cuisine', 58, 'CREATE INDEX "UserManager_userpreferences_preferred_cuisine_cuisine_id_b8a492d0" ON "UserManager_userpreferences_preferred_cuisine" ("cuisine_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'RecommendationManager_entertainment', 'RecommendationManager_entertainment', 59, 'CREATE TABLE "RecommendationManager_entertainment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "description" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'UserManager_userpreferences_preferred_entertainment', 'UserManager_userpreferences_preferred_entertainment', 42, 'CREATE TABLE "UserManager_userpreferences_preferred_entertainment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userpreferences_id" char(32) NOT NULL REFERENCES "UserManager_userpreferences" ("id") DEFERRABLE INITIALLY DEFERRED, "entertainment_id" bigint NOT NULL REFERENCES "RecommendationManager_entertainment" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_entertainment_userpreferences_id_entertainment_id_38b3f57b_uniq', 'UserManager_userpreferences_preferred_entertainment', 43, 'CREATE UNIQUE INDEX "UserManager_userpreferences_preferred_entertainment_userpreferences_id_entertainment_id_38b3f57b_uniq" ON "UserManager_userpreferences_preferred_entertainment" ("userpreferences_id", "entertainment_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_entertainment_userpreferences_id_d5c0c1c6', 'UserManager_userpreferences_preferred_entertainment', 52, 'CREATE INDEX "UserManager_userpreferences_preferred_entertainment_userpreferences_id_d5c0c1c6" ON "UserManager_userpreferences_preferred_entertainment" ("userpreferences_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_entertainment_entertainment_id_36cdb081', 'UserManager_userpreferences_preferred_entertainment', 60, 'CREATE INDEX "UserManager_userpreferences_preferred_entertainment_entertainment_id_36cdb081" ON "UserManager_userpreferences_preferred_entertainment" ("entertainment_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'RecommendationManager_timeofday', 'RecommendationManager_timeofday', 61, 'CREATE TABLE "RecommendationManager_timeofday" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "description" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'UserManager_userpreferences_preferred_time', 'UserManager_userpreferences_preferred_time', 44, 'CREATE TABLE "UserManager_userpreferences_preferred_time" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userpreferences_id" char(32) NOT NULL REFERENCES "UserManager_userpreferences" ("id") DEFERRABLE INITIALLY DEFERRED, "timeofday_id" bigint NOT NULL REFERENCES "RecommendationManager_timeofday" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_time_userpreferences_id_timeofday_id_b3d10128_uniq', 'UserManager_userpreferences_preferred_time', 45, 'CREATE UNIQUE INDEX "UserManager_userpreferences_preferred_time_userpreferences_id_timeofday_id_b3d10128_uniq" ON "UserManager_userpreferences_preferred_time" ("userpreferences_id", "timeofday_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_time_userpreferences_id_27fecf38', 'UserManager_userpreferences_preferred_time', 53, 'CREATE INDEX "UserManager_userpreferences_preferred_time_userpreferences_id_27fecf38" ON "UserManager_userpreferences_preferred_time" ("userpreferences_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_time_timeofday_id_3645db95', 'UserManager_userpreferences_preferred_time', 62, 'CREATE INDEX "UserManager_userpreferences_preferred_time_timeofday_id_3645db95" ON "UserManager_userpreferences_preferred_time" ("timeofday_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'RecommendationManager_weather', 'RecommendationManager_weather', 63, 'CREATE TABLE "RecommendationManager_weather" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "description" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'UserManager_userpreferences_preferred_weather', 'UserManager_userpreferences_preferred_weather', 46, 'CREATE TABLE "UserManager_userpreferences_preferred_weather" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userpreferences_id" char(32) NOT NULL REFERENCES "UserManager_userpreferences" ("id") DEFERRABLE INITIALLY DEFERRED, "weather_id" bigint NOT NULL REFERENCES "RecommendationManager_weather" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_weather_userpreferences_id_weather_id_c2086a0b_uniq', 'UserManager_userpreferences_preferred_weather', 47, 'CREATE UNIQUE INDEX "UserManager_userpreferences_preferred_weather_userpreferences_id_weather_id_c2086a0b_uniq" ON "UserManager_userpreferences_preferred_weather" ("userpreferences_id", "weather_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_weather_userpreferences_id_ad851e8f', 'UserManager_userpreferences_preferred_weather', 54, 'CREATE INDEX "UserManager_userpreferences_preferred_weather_userpreferences_id_ad851e8f" ON "UserManager_userpreferences_preferred_weather" ("userpreferences_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_weather_weather_id_3a3de4f8', 'UserManager_userpreferences_preferred_weather', 64, 'CREATE INDEX "UserManager_userpreferences_preferred_weather_weather_id_3a3de4f8" ON "UserManager_userpreferences_preferred_weather" ("weather_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'UserManager_userpreferences_preferred_indoor_activities', 'UserManager_userpreferences_preferred_indoor_activities', 68, 'CREATE TABLE "UserManager_userpreferences_preferred_indoor_activities" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userpreferences_id" char(32) NOT NULL REFERENCES "UserManager_userpreferences" ("id") DEFERRABLE INITIALLY DEFERRED, "indooractivity_id" bigint NOT NULL REFERENCES "RecommendationManager_indooractivity" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'UserManager_userpreferences_preferred_outdoor_activities', 'UserManager_userpreferences_preferred_outdoor_activities', 69, 'CREATE TABLE "UserManager_userpreferences_preferred_outdoor_activities" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userpreferences_id" char(32) NOT NULL REFERENCES "UserManager_userpreferences" ("id") DEFERRABLE INITIALLY DEFERRED, "outdooractivity_id" bigint NOT NULL REFERENCES "RecommendationManager_outdooractivity" ("id") DEFERRABLE INITIALLY DEFERRED)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_indoor_activities_userpreferences_id_indooractivity_id_8ad1bd87_uniq', 'UserManager_userpreferences_preferred_indoor_activities', 70, 'CREATE UNIQUE INDEX "UserManager_userpreferences_preferred_indoor_activities_userpreferences_id_indooractivity_id_8ad1bd87_uniq" ON "UserManager_userpreferences_preferred_indoor_activities" ("userpreferences_id", "indooractivity_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_indoor_activities_userpreferences_id_8cd6d0dc', 'UserManager_userpreferences_preferred_indoor_activities', 74, 'CREATE INDEX "UserManager_userpreferences_preferred_indoor_activities_userpreferences_id_8cd6d0dc" ON "UserManager_userpreferences_preferred_indoor_activities" ("userpreferences_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_indoor_activities_indooractivity_id_f43bc8f0', 'UserManager_userpreferences_preferred_indoor_activities', 75, 'CREATE INDEX "UserManager_userpreferences_preferred_indoor_activities_indooractivity_id_f43bc8f0" ON "UserManager_userpreferences_preferred_indoor_activities" ("indooractivity_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_outdoor_activities_userpreferences_id_outdooractivity_id_d05f5b3b_uniq', 'UserManager_userpreferences_preferred_outdoor_activities', 73, 'CREATE UNIQUE INDEX "UserManager_userpreferences_preferred_outdoor_activities_userpreferences_id_outdooractivity_id_d05f5b3b_uniq" ON "UserManager_userpreferences_preferred_outdoor_activities" ("userpreferences_id", "outdooractivity_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_outdoor_activities_userpreferences_id_21bd30dd', 'UserManager_userpreferences_preferred_outdoor_activities', 76, 'CREATE INDEX "UserManager_userpreferences_preferred_outdoor_activities_userpreferences_id_21bd30dd" ON "UserManager_userpreferences_preferred_outdoor_activities" ("userpreferences_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UserManager_userpreferences_preferred_outdoor_activities_outdooractivity_id_6b745d49', 'UserManager_userpreferences_preferred_outdoor_activities', 78, 'CREATE INDEX "UserManager_userpreferences_preferred_outdoor_activities_outdooractivity_id_6b745d49" ON "UserManager_userpreferences_preferred_outdoor_activities" ("outdooractivity_id")');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'UserManager_userpreferences', 'UserManager_userpreferences', 79, 'CREATE TABLE "UserManager_userpreferences" ("id" char(32) NOT NULL PRIMARY KEY, "updated_at" datetime NOT NULL, "created_at" datetime NOT NULL, "user_id" char(32) NOT NULL UNIQUE REFERENCES "AuthManager_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED, "preferred_location" varchar(255) NOT NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_UserManager_userpreferences_1', 'UserManager_userpreferences', 80, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_UserManager_userpreferences_2', 'UserManager_userpreferences', 81, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'RecommendationManager_indooractivity', 'RecommendationManager_indooractivity', 48, 'CREATE TABLE "RecommendationManager_indooractivity" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "description" text NULL)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'RecommendationManager_outdooractivity', 'RecommendationManager_outdooractivity', 49, 'CREATE TABLE "RecommendationManager_outdooractivity" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "description" text NULL)');
